### ISSUE TITLE
error codes are impossible to decipher 

### ISSUE THREAD

**Issue by Lunarequest** [hsluoyz/WlanHelper#2]
if wlan helper gives a error code it would be nice if there was a pdf or something like that. this should contain any error codes and what the error means

**Comment by hsluoyz** [comment]
You can google that error code together with the function name. That will probably point you to a MSDN documentation page.

**Comment by Lunarequest** [comment]
i checked the internet and there are no documents saying the error codes on the internet. i would not mind helping create a document with error codes and their meanings,

**Comment by hsluoyz** [comment]
Can you paste your full error output from CMD here?

**Comment by Lunarequest** [comment]
SetInterface error, error code = 1168 // this means interface does not exist
SetInterface error, error code = 5  // needs higher privileges. 
these are 2 error codes i managed to recreate as you can see for a beginner it is very confusing. i feel that it would be better to create a pdf or txt file with all error that are possible and what they mean to help debugging

**Comment by hsluoyz** [comment]
@advaithm you should use the latest version WlanHelper, the latest version will report the error message as well, see: https://github.com/nmap/nmap/issues/990#issuecomment-342884345

**Comment by devilsnare007** [comment]
My network card is 'Intel WiFi6 AX200'. It goes into monitor mode with Tamosoft Commview for WiFi OR using kali linux, but when using wlanhelper (on windows 10) to change the interface mode to 'monitor' it gives an error:
`C:\Windows\System32\Npcap>wlanhelper "Wi-Fi" mode monitor
Error: SetWlanOperationMode::SetInterface error, error code = 50 (The request is not supported)
Failure`

**Comment by hsluoyz** [comment]
@devilsnare007 it's usually because the Windows driver for your NIC doesn't implement the monitor mode.

**Comment by devilsnare007** [comment]
> @devilsnare007 it's usually because the Windows driver for your NIC doesn't implement the monitor mode.

forgive my ignorance, but if it is indeed a Windows driver issue - why would it work fine when using Commview (on Windows) OR perhaps Commview implements its own driver which npcap does not - in which case it indicates npcap's limitation and not necessarily a windows driver issue..

**Comment by hsluoyz** [comment]
@devilsnare007 got it. Please send the issue to: https://github.com/nmap/npcap/issues then.
